version: '3.5'
services:
  lightmetercontrolcenter:
    image: lightmeter/controlcenter:${CONTROL_VERSION}
    restart: always
    env_file: ./.env
    ports:
      - "8088:8080"
    volumes:
      - "/var/log/:/logs:ro"
      - "/var/lib/lightmeter_workspace/:/workspace"
    command: -workspace /workspace -watch_dir /logs
