#!/usr/bin/env bash

set -Eeuo pipefail

err_report() {
	echo "An error occurded on line $1 of this script."
}

trap 'err_report $LINENO' ERR

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

update_env_file () {
	varname="$1"
	varvalue="$2"
	if ! grep -q "$varname" ./.env; then
	echo "$varname=$varvalue" >> ./.env
		else
	sed -i "/$varname/c $varname=$varvalue" ./.env
	fi
}

CONTROL_VERSION=$(git ls-remote --refs --tags https://gitlab.com/lightmeter/controlcenter.git/ | grep -v 'RC' | sort -t '/' -k 4 -V | awk -F/ '{ print $4 }' | tail -1)

mkdir -p /var/lib/lightmeter_workspace

touch $script_dir/.env
update_env_file CONTROL_VERSION $CONTROL_VERSION
update_env_file DOCKERLOGGING_MAXFILE 2
update_env_file DOCKERLOGGING_MAXSIZE 200k

docker-compose up -d

cat <<-EOF >"/etc/apache2/ucs-sites.conf.d/lightmeter.conf"

##################################################################
# generated by lightmeter app join script, do not edit manually  #
##################################################################

ProxyPass /lightmeter/ http://127.0.0.1:8088/ retry=0

EOF

invoke-rc.d apache2 reload

